#!/usr/bin/env python3


import os
import argparse
import torch
from transformers import AutoTokenizer

# FORCE SYNCHRONOUS CUDA EXEUCTION TO CATCH EXACT KERNEL CRASHES
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

# IMPORT YOUR EXACT API
from comp_inference import load_compressed_model_with_auto_model


def inject_nan_detectors(model):
    """Hooks into every layer to instantly catch the exact module producing NaNs."""

    def nan_hook(module, inputs, outputs):
        if isinstance(outputs, tuple):
            out_tensor = outputs[0]
        else:
            out_tensor = outputs

        if isinstance(out_tensor, torch.Tensor) and out_tensor.is_floating_point():
            if torch.isnan(out_tensor).any():
                print(
                    f"\n[FATAL] NaNs DETECTED IN OUTPUT OF: {module.__class__.__name__}"
                )
                print(f"Module shape details: {out_tensor.shape}")
                raise RuntimeError(f"NaNs generated by {module.__class__.__name__}")

    for name, module in model.named_modules():
        # Only attach to leaf modules
        if len(list(module.children())) == 0:
            module.register_forward_hook(nan_hook)

    print("NaN detectors successfully injected into all layers.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", type=str, required=True)
    parser.add_argument("--compressed_path", type=str, required=True)
    parser.add_argument("--prompt", type=str, default="Who is Linus Torvalds?")
    args = parser.parse_args()

    # Load strictly the RANS backend to prevent Accelerate/VRAM pollution
    model = load_compressed_model_with_auto_model(
        model_id=args.model_name, safetensors_path=args.compressed_path
    )

    inject_nan_detectors(model)
    tokenizer = AutoTokenizer.from_pretrained(args.model_name)
    inputs = tokenizer(args.prompt, return_tensors="pt").to("cuda")

    print("\n--- Phase 1: WARMUP PASS (max_new_tokens=2) ---")
    try:
        with torch.no_grad():
            _ = model.generate(**inputs, max_new_tokens=2)
        print("Warmup Successful! Workspace memory is stable.")
    except Exception as e:
        print(f"\nCRASH DURING WARMUP: {e}")
        exit(1)

    print("\n--- Phase 2: BENCHMARK PASS (max_new_tokens=16) ---")
    try:
        with torch.no_grad():
            outputs = model.generate(**inputs, max_new_tokens=16)
        print("Benchmark Successful!")
        print("Output:", tokenizer.decode(outputs[0]))
    except Exception as e:
        print(f"\nCRASH DURING BENCHMARK: {e}")
